--------------------------------------------------------
--  File created - Pazar-Temmuz-30-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "C##YALCIN"."BOOK" 
   (	"ID" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(40 BYTE), 
	"AUTHOR" VARCHAR2(20 BYTE), 
	"PUBLISHER" VARCHAR2(20 BYTE), 
	"ISAVAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ISSUE
--------------------------------------------------------

  CREATE TABLE "C##YALCIN"."ISSUE" 
   (	"BOOK_ID" VARCHAR2(20 BYTE), 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"ISSUE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"RENEW_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "C##YALCIN"."MEMBER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"MOBILE" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##YALCIN"."EMPLOYEE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
REM INSERTING into C##YALCIN.BOOK
SET DEFINE OFF;
Insert into C##YALCIN.BOOK (ID,TITLE,AUTHOR,PUBLISHER,ISAVAIL) values ('10','Kim Korkar Javadan','Alper Akalýn','Abaküs','yes');
Insert into C##YALCIN.BOOK (ID,TITLE,AUTHOR,PUBLISHER,ISAVAIL) values ('11','Bukre','Kahraman Tazeoðlu','Destek Yayýnlarý','yes');
Insert into C##YALCIN.BOOK (ID,TITLE,AUTHOR,PUBLISHER,ISAVAIL) values ('12','Siyah Süt','Elif Þafak','Doðan Kitapçýlýk','yes');
Insert into C##YALCIN.BOOK (ID,TITLE,AUTHOR,PUBLISHER,ISAVAIL) values ('44','Merhaba Dünya','James Gosling','W3Schools','yes');
REM INSERTING into C##YALCIN.ISSUE
SET DEFINE OFF;
REM INSERTING into C##YALCIN.MEMBER
SET DEFINE OFF;
Insert into C##YALCIN.MEMBER (ID,NAME,MOBILE,MAIL) values ('1','Mevlana Yalçýn','0555555555','mail@gmail.com');
Insert into C##YALCIN.MEMBER (ID,NAME,MOBILE,MAIL) values ('2','James Gosling','05544444444','abc@gmail.com');
Insert into C##YALCIN.MEMBER (ID,NAME,MOBILE,MAIL) values ('3','Aziz Sancar','05466666666','def@hotmail.com');
Insert into C##YALCIN.MEMBER (ID,NAME,MOBILE,MAIL) values ('4','Linus Torvalds','12344455555','fgh@outlook.com');
--------------------------------------------------------
--  DDL for Index BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##YALCIN"."BOOK_PK" ON "C##YALCIN"."BOOK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##YALCIN"."MEMBER_PK" ON "C##YALCIN"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "C##YALCIN"."BOOK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##YALCIN"."BOOK" MODIFY ("ISAVAIL" NOT NULL ENABLE);
  ALTER TABLE "C##YALCIN"."BOOK" ADD CONSTRAINT "BOOK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "C##YALCIN"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##YALCIN"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ISSUE
--------------------------------------------------------

  ALTER TABLE "C##YALCIN"."ISSUE" ADD PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ISSUE
--------------------------------------------------------

  ALTER TABLE "C##YALCIN"."ISSUE" ADD FOREIGN KEY ("BOOK_ID")
	  REFERENCES "C##YALCIN"."BOOK" ("ID") ENABLE;
  ALTER TABLE "C##YALCIN"."ISSUE" ADD FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "C##YALCIN"."MEMBER" ("ID") ENABLE;
